<?php

return [
    "vi" => [
        "home" => "Trang chủ",
        "services" => "Dịch vụ",
        "create_post"   => "Tạo tin đăng",
        "title_slider_1"      => "Nền&nbsp;tảng&nbsp;kết&nbsp;nối&nbsp;<span class=\"highLight\">Dự&nbsp;án&nbsp;-&nbsp;Đối&nbsp;tác&nbsp;-&nbsp;Đầu&nbsp;tư</span>&nbsp;toàn&nbsp;diện",
        "description_slider_1"  => "Đăng dự án, tìm nhà đầu tư, kết nối đối tác, xây dựng hệ thống – tất cả trong một nền tảng.",
        "text_1_of_button_slider_1"  => "Nhận <span>tin đăng miễn phí</span>",
        "text_2_of_button_slider_1"  => "Kết nối ngay với hàng ngàn đối tác",
        "banner_home_array" => [
            [
                "src"   => "https://hoptackinhdoanh.storage.googleapis.com/storage/images/icon-ket-noi-nhanh-chong.webp",
                "title" => "Kết nối nhanh chóng",
                "description" => "Đăng dự án, tìm nhà đầu tư, kết nối đối tác với vài bước đơn giản",
            ],
            [
                "src"   => "https://hoptackinhdoanh.storage.googleapis.com/storage/images/icon-ho-tro-toan-dien.webp?213334423",
                "title" => "Hỗ trợ toàn diện",
                "description" => "Từ PR, pháp lý đến marketing và xây dựng hệ thống",
            ],
            [
                "src"   => "https://hoptackinhdoanh.storage.googleapis.com/storage/images/icon-chuyen-gia-dong-hanh.webp",
                "title" => "Chuyên gia đồng hành",
                "description" => "Tư vấn 1:1 cùng đội ngũ giàu kinh nghiệm – rõ ràng, hiệu quả",
            ],
        ],
        "view_more" => "Xem thêm",
        "no_matching_posts" => "Không có bài đăng phù hợp!",
        "why_choose_us_title"   => "Giá trị chúng tôi mang lại",
        "why_choose_us_items"   => [
            [
                "title"  => "Kết Nối Thông Minh – Tối Ưu Cơ Hội",
                "description" => "Hệ thống AI tự động ghép nối dự án - nhà đầu tư - startup phù hợp trong thời gian thực, tăng khả năng thành công nhờ phân tích nhu cầu chi tiết.",
            ],
            [
                "title"  => "Dịch Vụ Trọn Gói – Hỗ Trợ Toàn Diện",
                "description" => "Cung cấp pháp lý, marketing, tài chính và xây dựng mô hình kinh doanh trên một nền tảng – bạn tập trung ý tưởng, chúng tôi xử lý phần còn lại.",
            ],
            [
                "title"  => "Triển Khai Nhanh – Hiệu Quả Ngay",
                "description" => "Giao diện đơn giản, công cụ quảng bá thông minh giúp tiếp cận đối tác trong 72 giờ, rút ngắn 30% thời gian từ ý tưởng đến thực thi.",
            ],
            [
                "title"  => "Mạng Lưới Chuyên Gia – Tư Vấn Sâu",
                "description" => "Kết nối với 500+ nhà đầu tư, luật sư và chuyên gia giàu kinh nghiệm, hỗ trợ từ ý tưởng đến khi mở rộng quy mô.",
            ],
            [
                "title"  => "Minh Bạch – Bảo Mật – Bền Vững",
                "description" => "Quy trình kiểm duyệt chặt chẽ, xác thực đa lớp – đảm bảo thông tin minh bạch, bảo mật và đồng hành lâu dài trong mọi hợp tác.",
            ],
        ],
        "top_partner"  => "Đối tác hàng đầu",
        "post"  => "tin đăng",
        "article"  => "bài viết",
        "featured_articles" => "Bài viết nổi bật",
        "registry_emali_success_title" => "Đăng ký email thành công!",
        "registry_emali_success_body" => "<div>Cảm ơn bạn đã đăng ký nhận tin!</div><div>Trong thời gian tới nếu có bất kỳ thông tin mới nào <a href=\"/\"><strong>Hoptackinhdoanh.com</strong></a> sẽ gửi cho bạn đầu tiên.</div>",
        "registry_emali_error_title" => "Đăng ký email thất bại!",
        "registry_emali_error_body" => "<div>Có lỗi xảy ra, vui lòng thử lại sau.</div>",
        "notice_construction_create_post_title" => "Tính năng này đang được cập nhật!",
        "notice_construction_create_post_body" => "<div>Các tính năng để bạn chủ động <strong>Đăng tin</strong>, <strong>Đẩy tin</strong> và <strong>Quản lý tin</strong> hiện đang được chúng tôi nâng cấp để mang lại trải nghiệm tốt hơn.</div><div>Trong thời gian này, nếu bạn cần đăng tin, vui lòng gửi thông tin đến địa chỉ mail <a href=mailto:contact@hoptackinhdoanh.com><strong>contact@hoptackinhdoanh.com</strong></a>. Chúng tôi sẽ hỗ trợ bạn nhanh chóng!</div>",
        "notice_construction_report_title" => "Tính năng này đang được cập nhật!",
        "notice_construction_report_body" => "<div>Các tính năng <strong>Báo cáo lừa đảo</strong> và <strong>Góp ý</strong> hiện đang được chúng tôi nâng cấp nhằm đảm bảo thân thiện hơn cho tất cả người dùng.</div><div>Nếu bạn cần gửi báo cáo hoặc góp ý trong thời gian này, vui lòng gửi thông tin đến địa chỉ mail <a href=\"mailto:contact@hoptackinhdoanh.com\"><strong>contact@hoptackinhdoanh.com</strong></a>. Chúng tôi trân trọng mọi phản hồi và sẽ xử lý nhanh nhất có thể!</div>",
        "no_matching_reports" => "Hiện chưa có tin nào!",
        "question_and_answer" => "Câu hỏi thường gặp",
        "filter_by_category"    => "Lọc theo danh mục",
        "not_infomation_yet"    => "Chưa có thông tin!",
        "official_business_information" => "Thông tin doanh nghiệp chính thức",

        "table_of_contents" => "Mục lục",
        "share" => "Chia sẻ",
        "options" => "Tùy chọn",
        "propose" => "Đề xuất",
        "favourite" => "Yêu thích",
        "newest" => "Mới nhất",
        "oldest" => "Cũ nhất",
        "bestseller" => "Bán chạy",
        "browse_by" => "Duyệt theo",
        "sort_by" => "Sắp xếp theo",
        "filter_by" => "Lọc theo",
        "advanced_filter" => "Bộ lọc nâng cao",
        "all" => "Tất cả",
        "undefined" => "Không xác định",
        "payment_method" => "Phương thức thanh toán",
        "fee" => "Phí",
        "payment_fee" => "Phí thanh toán",
        "view_all" => "Xem tất cả",
        "login_name_com_vn" => "Đăng nhập hoptackinhdoanh.com",
        "login_email" => "Email đăng nhập",
        "password" => "Mật khẩu",
        "remember_me" => "Ghi nhớ đăng nhập",
        "login" => "Đăng nhập",
        "or_login_with" => "Hoặc đăng nhập bằng",
        "logout" => "Đăng xuất",
        "email" => "Email",
        "what_do_you_want_to_find_today" => "Tìm Dự án, Đối tác, Cơ hội đầu tư,...",
        "search" => "Tìm kiếm",
        "your_cart_is_empty" => "Giỏ hàng của bạn trống!",
        "continue_shopping" => "Mua sắm",
        "link_page_category" => "san-pham-zenpot",
        "list_type_search" => [
            "all"           => "Tất cả",
            "category_info" => "Dự án kinh doanh",
            "paid_wallpaper" => "Dự án bất động sản",
            "free_wallpaper" => "Đối tác",
            "article" => "Quỹ đầu tư",
        ],
        "loading" => "Đang tải...",
        "copyright" => "Bản quyền ® ".date('Y')." <a href=\"" . config('app.url') . "\" aria-label=\"" . config('app.name') . "\"><strong>" . config('app.name') . "</strong></a>. Thiết kế và phát triển bởi PhamVanPhu. Mọi quyền được bảo lưu.",
    ],
];